### ISSUE TITLE
可视化过程报错~

### ISSUE THREAD

**Issue by lsm2842035890** [daohu527/imap#117]
第一次设置好虚拟环境运行这个可视化项目一点问题都没有，今天再次运行就报错了，python=3.8,用pip install -e . 安装的包
(imap) lsm@lsm-B760M-AORUS-ELITE-AX:~/imap/imap$ imap -m data/borregas_ave.txt
Traceback (most recent call last):
  File "/home/lsm/anaconda3/envs/imap/bin/imap", line 5, in <module>
    from imap.main import main
  File "/home/lsm/imap/imap/main.py", line 26, in <module>
    from imap.lib.draw import add_editor, show_map
  File "/home/lsm/imap/imap/lib/draw.py", line 23, in <module>
    fig, ax = plt.subplots(figsize=(20, 20))
  File "/home/lsm/anaconda3/envs/imap/lib/python3.8/site-packages/matplotlib/pyplot.py", line 1501, in subplots
    fig = figure(**fig_kw)
  File "/home/lsm/anaconda3/envs/imap/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "/home/lsm/anaconda3/envs/imap/lib/python3.8/site-packages/matplotlib/pyplot.py", line 840, in figure
    manager = new_figure_manager(
  File "/home/lsm/anaconda3/envs/imap/lib/python3.8/site-packages/matplotlib/pyplot.py", line 384, in new_figure_manager
    return _get_backend_mod().new_figure_manager(*args, **kwargs)
  File "/home/lsm/anaconda3/envs/imap/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3574, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/lsm/anaconda3/envs/imap/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3579, in new_figure_manager_given_figure
    return cls.FigureCanvas.new_manager(figure, num)
  File "/home/lsm/anaconda3/envs/imap/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1742, in new_manager
    return cls.manager_class.create_with_canvas(cls, figure, num)
  File "/home/lsm/anaconda3/envs/imap/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 507, in create_with_canvas
    manager = cls(canvas, num, window)
  File "/home/lsm/anaconda3/envs/imap/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 457, in __init__
    super().__init__(canvas, num)
  File "/home/lsm/anaconda3/envs/imap/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2832, in __init__
    self.toolbar = self._toolbar2_class(self.canvas)
  File "/home/lsm/anaconda3/envs/imap/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 630, in __init__
    self._buttons[text] = button = self._Button(
  File "/home/lsm/anaconda3/envs/imap/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 834, in _Button
    NavigationToolbar2Tk._set_image_for_button(self, b)
  File "/home/lsm/anaconda3/envs/imap/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 770, in _set_image_for_button
    image = ImageTk.PhotoImage(im.resize((size, size)), master=self)
  File "/home/lsm/anaconda3/envs/imap/lib/python3.8/site-packages/PIL/Image.py", line 2305, in resize
    im = im.resize(size, resample, box)
  File "/home/lsm/anaconda3/envs/imap/lib/python3.8/site-packages/PIL/Image.py", line 2328, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0

**Comment by daohu527** [comment]
@lsm2842035890 I tested it and there is no problem!

The env
```shell
Python 3.12.5
```

**Comment by lsm2842035890** [comment]
谢谢~刚重启一下电脑就又好了
