### ISSUE TITLE
Conversion failure

### ISSUE THREAD

**Issue by joseph16388** [daohu527/imap#63]
Very useful conversion tool, but I encountered conversion failure for
[straight_500m.txt](https://github.com/daohu527/imap/files/10045982/straight_500m.txt) ，Please change the txt suffix to the xodr suffix because of upload restrictions

I used the imap -m straight_500m.xodr command, and the result showed that XXX... AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by daohu527** [comment]
I fixed the error, and there are some questions to be confirmed here, for example
1. what are you using to generate opendrive maps?
2. Since I did not find out which attributes are required and which are not in the specification, it is difficult to solve the problem of missing some attributes when different software generates maps

**Comment by joseph16388** [comment]
> I fixed the error, and there are some questions to be confirmed here, for example
> 
> 1. what are you using to generate opendrive maps?
> 2. Since I did not find out which attributes are required and which are not in the specification, it is difficult to solve the problem of missing some attributes when different software generates maps

1、I get a lot of xodr files from lgsvl's store (https://content.lgsvlsimulator.com/) and esmini. I used your library to try to convert from opendrive to apollo maps, but most failed for reasons like AttributeError: 'NoneType' object has no attribute 'XXX'
2、Do you have the opendrive format of the borregas_ave map here? Why is the number of xy coordinates so large? what elements of opendrive reflect this？
Thank you!

**Comment by daohu527** [comment]
1. This may be because some attributes are not filled in, of course, it may also depend on whether the specification stipulates that these fields are required.
2. no, I don't have. borregas_ave is use UTM cor, so the x-y is large

**Comment by Kevin23cvetd** [comment]
imap -f -i  sssssr.xodr -o apollo_map.txt
Traceback (most recent call last):
  File "/usr/local/bin/imap", line 11, in <module>
    load_entry_point('imap-box==0.1.6', 'console_scripts', 'imap')()
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/main.py", line 108, in main
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/main.py", line 31, in convert_map_format
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/lib/convertor.py", line 118, in __init__
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/lib/opendrive/map.py", line 117, in load
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/lib/opendrive/map.py", line 79, in post_process
KeyError: '1837'
chenghong@CNSHA0206L:~/Downloads$ imap -f -i  sssssr.xodr -o apollo_map.txt
Traceback (most recent call last):
  File "/usr/local/bin/imap", line 11, in <module>
    load_entry_point('imap-box==0.1.6', 'console_scripts', 'imap')()
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/main.py", line 108, in main
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/main.py", line 31, in convert_map_format
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/lib/convertor.py", line 118, in __init__
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/lib/opendrive/map.py", line 117, in load
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/lib/opendrive/map.py", line 79, in post_process
KeyError: '1837'
