### ISSUE TITLE
TypeError: None has type NoneType, but expected one of: int, long

### ISSUE THREAD

**Issue by flutterhue** [daohu527/imap#70]
imap -m cologne_fortiib.xodr 
parse_geo_reference is +proj=tmerc +lat_0=50.9961872 +lon_0=6.8882864 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +geoidgrids=egm96_15.gtx +vunits=m +no_defs : 
Traceback (most recent call last):
  File "/home/xiao/Project/Env/py37/bin/imap", line 8, in <module>
    sys.exit(main())
  File "/home/xiao/Project/Env/py37/lib/python3.7/site-packages/imap/main.py", line 98, in main
    show_open_drive_map(args.map)
  File "/home/xiao/Project/Env/py37/lib/python3.7/site-packages/imap/main.py", line 41, in show_open_drive_map
    opendrive2apollo.convert()
  File "/home/xiao/Project/Env/py37/lib/python3.7/site-packages/imap/lib/convertor.py", line 577, in convert
    self.convert_roads()
  File "/home/xiao/Project/Env/py37/lib/python3.7/site-packages/imap/lib/convertor.py", line 530, in convert_roads
    pb_last_right_section = self.convert_lane(xodr_road, pb_road)
  File "/home/xiao/Project/Env/py37/lib/python3.7/site-packages/imap/lib/convertor.py", line 443, in convert_lane
    pb_lane = self.create_lane(xodr_road, lane_section, idx, lane)
  File "/home/xiao/Project/Env/py37/lib/python3.7/site-packages/imap/lib/convertor.py", line 380, in create_lane
    self.add_basic_info(pb_lane, xodr_road, idx, lane)
  File "/home/xiao/Project/Env/py37/lib/python3.7/site-packages/imap/lib/convertor.py", line 168, in add_basic_info
    pb_lane.type = to_pb_lane_type(lane.lane_type)
TypeError: None has type NoneType, but expected one of: int, long

**Comment by flutterhue** [comment]
[opendrive map](https://pan.baidu.com/s/4faOrvYq)

**Comment by daohu527** [comment]
Your map have lane without `lane type`. The biggest problem with opendrive is that there is no required field, but we use this field to generate road boundaries

```
9.5.3. Lane type
The lane type is defined per lane. A lane type defines the main purpose of a lane and its corresponding traffic rules.

The available lane types are:
```

**Comment by flutterhue** [comment]
> Thank you for your reply
