### ISSUE TITLE
cannot use imap

### ISSUE THREAD

**Issue by dajiba6** [daohu527/imap#77]
Command 'imap' not found, did you mean:

  command 'nmap' from snap nmap (7.93)
  command 'umap' from deb libunicode-map8-perl (0.13+dfsg-4build6)
  command 'nmap' from deb nmap (7.80+dfsg1-2build1)
  command 'imapd' from deb courier-imap (5.0.6+1.0.6-1build2)
  command 'amap' from deb amap-align (2.2+git20080214.600fc29+dfsg-1build1)
  command 'tmap' from deb emboss (6.6.0+dfsg-7ubuntu2)
  command 'jmap' from deb openjdk-16-jdk-headless (16.0.1+9-1~20.04)
  command 'jmap' from deb openjdk-17-jdk-headless (17.0.6+10-0ubuntu1~20.04.1)
  command 'jmap' from deb openjdk-8-jdk-headless (8u362-ga-0ubuntu1~20.04.1)
  command 'jmap' from deb openjdk-13-jdk-headless (13.0.7+5-0ubuntu1~20.04)
  command 'imgp' from deb imgp (2.7-1)
  command 'zmap' from deb zmap (2.1.1-2build3)
  command 'gmap' from deb gmap (2020-04-08+ds1-1)
  command 'smap' from deb slurm-client (19.05.5-1)

See 'snap info <snapname>' for additional versions.

========but i already installed it.==========

pip3 install imap_box
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: imap_box in ./.local/lib/python3.8/site-packages (0.1.6)
Requirement already satisfied: protobuf<=3.19.4 in /usr/lib/python3/dist-packages (from imap_box) (3.6.1)
Requirement already satisfied: record-msg<=0.1.1 in ./.local/lib/python3.8/site-packages (from imap_box) (0.1.1)
Requirement already satisfied: pyproj in ./.local/lib/python3.8/site-packages (from imap_box) (3.5.0)
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (from imap_box) (3.1.2)
Requirement already satisfied: lzf in ./.local/lib/python3.8/site-packages (from record-msg<=0.1.1->imap_box) (0.1)
Requirement already satisfied: opencv-python in ./.local/lib/python3.8/site-packages (from record-msg<=0.1.1->imap_box) (4.7.0.72)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from pyproj->imap_box) (2019.11.28)
Requirement already satisfied: cffi>=1.0.0 in ./.local/lib/python3.8/site-packages (from lzf->record-msg<=0.1.1->imap_box) (1.15.1)
Requirement already satisfied: numpy>=1.17.0 in /usr/lib/python3/dist-packages (from opencv-python->record-msg<=0.1.1->imap_box) (1.17.4)
Requirement already satisfied: pycparser in ./.local/lib/python3.8/site-packages (from cffi>=1.0.0->lzf->record-msg<=0.1.1->imap_box) (2.21)

**Comment by dajiba6** [comment]
WARNING: The script pyproj is installed in '/home/cyn/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  DEPRECATION: lzf is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for lzf ... done
  WARNING: The script imap is installed in '/home/cyn/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by dajiba6** [comment]
after adding the path, it still doesn't work

Traceback (most recent call last):
  File "/home/cyn/.local/bin/imap", line 5, in <module>
    from imap.main import main
  File "/home/cyn/.local/lib/python3.8/site-packages/imap/main.py", line 26, in <module>
    from imap.lib.draw import add_editor, show_map
  File "/home/cyn/.local/lib/python3.8/site-packages/imap/lib/draw.py", line 21, in <module>
    from imap.map import Map
  File "/home/cyn/.local/lib/python3.8/site-packages/imap/map.py", line 20, in <module>
    from modules.map.proto import map_pb2
  File "/home/cyn/.local/lib/python3.8/site-packages/modules/map/proto/map_pb2.py", line 14, in <module>
    from modules.map.proto import map_clear_area_pb2 as modules_dot_map_dot_proto_dot_map__clear__area__pb2
  File "/home/cyn/.local/lib/python3.8/site-packages/modules/map/proto/map_clear_area_pb2.py", line 14, in <module>
    from modules.map.proto import map_id_pb2 as modules_dot_map_dot_proto_dot_map__id__pb2
  File "/home/cyn/.local/lib/python3.8/site-packages/modules/map/proto/map_id_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

**Comment by dajiba6** [comment]
seems this is because the version of my protobuf is too high. The version it requires is lower than 3.19.4

**Comment by dajiba6** [comment]
thank you my friend. I love you.
