### ISSUE TITLE
您好，xodr地图可视化失败，转换apollo地图失败,有如下报错

### ISSUE THREAD

**Issue by Kevin23cvetd** [daohu527/imap#80]
imap -m sssssr.xodr 
Traceback (most recent call last):
  File "/usr/local/bin/imap", line 11, in <module>
    load_entry_point('imap-box==0.1.6', 'console_scripts', 'imap')()
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/main.py", line 98, in main
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/main.py", line 39, in show_open_drive_map
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/lib/convertor.py", line 118, in __init__
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/lib/opendrive/map.py", line 117, in load
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/lib/opendrive/map.py", line 79, in post_process
KeyError: '1837'
chenghong@CNSHA0206L:~/Downloads$ imap -f -i  sssssr.xodr -o apollo_map.txt
Traceback (most recent call last):
  File "/usr/local/bin/imap", line 11, in <module>
    load_entry_point('imap-box==0.1.6', 'console_scripts', 'imap')()
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/main.py", line 108, in main
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/main.py", line 31, in convert_map_format
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/lib/convertor.py", line 118, in __init__
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/lib/opendrive/map.py", line 117, in load
  File "/usr/local/lib/python3.8/dist-packages/imap_box-0.1.6-py3.8.egg/imap/lib/opendrive/map.py", line 79, in post_process
KeyError: '1837'

**Comment by daohu527** [comment]
The reason for the error is that the road with id 1837 cannot be found. You should check if junction's connection road does not contain road 1837
