### ISSUE TITLE
Missing input length check at `imap.imap.lib.common.calc_length`

### ISSUE THREAD

**Issue by xqgex** [daohu527/imap#84]
## Version

```bash
$ python3 -m pip show imap_box
Name: imap-box
Version: 0.1.6
Summary: High-resolution map visualization and conversion tool
Home-page: https://github.com/daohu527/imap
Author: daohu527
Author-email: daohu527@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python3.7/dist-packages
Requires: matplotlib, protobuf, pyproj, record-msg
Required-by: 
```

## Traceback

```python
Traceback (most recent call last):
  File "/usr/local/bin/imap", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/imap/main.py", line 108, in main
    convert_map_format(args.input, args.output)
  File "/usr/local/lib/python3.7/dist-packages/imap/main.py", line 34, in convert_map_format
    opendrive2apollo.convert()
  File "/usr/local/lib/python3.7/dist-packages/imap/lib/convertor.py", line 610, in convert
    self.convert_roads()
  File "/usr/local/lib/python3.7/dist-packages/imap/lib/convertor.py", line 561, in convert_roads
    xodr_road.process_lanes()
  File "/usr/local/lib/python3.7/dist-packages/imap/lib/opendrive/road.py", line 198, in process_lanes
    self.lanes.process_lane_sections(self.reference_line)
  File "/usr/local/lib/python3.7/dist-packages/imap/lib/opendrive/lanes.py", line 426, in process_lane_sections
    lane_section.process_lane(reference_line_in_section)
  File "/usr/local/lib/python3.7/dist-packages/imap/lib/opendrive/lanes.py", line 324, in process_lane
    left_boundary = lane.generate_boundary(left_boundary, self.s)
  File "/usr/local/lib/python3.7/dist-packages/imap/lib/opendrive/lanes.py", line 229, in generate_boundary
    self.length = calc_length(self.center_line)
  File "/usr/local/lib/python3.7/dist-packages/imap/lib/common.py", line 111, in calc_length
    if math.fabs(points[0].yaw - points[-1].yaw) < 0.01:
IndexError: list index out of range
```

## Fix

https://github.com/daohu527/imap/blob/e4afa8f0cc555f9fd41a8d32b5363f8c74dd7c2a/imap/lib/common.py#L114-L116

Check `if len(points) < 2:` and return `0` (`length`) if so.

## Suggested fix (+ typehint)

```python
def calc_length(points: List[Point3d]) -> float:
  length = .0
  if len(points) >= 2:
    if math.fabs(points[0].yaw - points[-1].yaw) < 0.01:
      # straight line
      p, q = points[0], points[-1]
      x = q.x - p.x
      y = q.y - p.y
      z = q.z - p.z
      length = math.sqrt(x**2 + y**2 + z**2)
    else:
      for p, q in zip(points, points[1:]):
        x = q.x - p.x
        y = q.y - p.y
        z = q.z - p.z
        length += math.sqrt(x**2 + y**2 + z**2)
  return length
```

**Comment by daohu527** [comment]
This kind of abnormal input is usually caused by file errors. You know that there is no road and only a point exists.
